### ISSUE TITLE
Happy Birthday

### ISSUE THREAD

**Issue by kevinklaes** [Resisty/irc_bots#2]
Panicbutt should sing Happy Birthday to a person when it's their birthday.

**Comment by Resisty** [comment]
I'm going to implement singing happy birthday to a person when asked to do so; I don't feel like even starting to figure out how to make the bot aware of nicks' birthdays.

**Comment by kevinklaes** [comment]
oh yeah, that's fine. :shipIt:

**Comment by Resisty** [comment]
Done in https://github.com/Resisty/irc_bots/commit/2cc7d6d68a82b64fa275689da59817db370d8069
